# Generated by Django 5.1.4 on 2024-12-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='gender',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name',
            name='surname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
