# Generated by Django 5.1.4 on 2024-12-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='member',
            field=models.ManyToManyField(to='members.name'),
        ),
    ]
